# Generated by Django 5.1.7 on 2025-03-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0097_coursetranslation_featured_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="plan_meta",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="plan_slug",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
