# Generated by Django 5.1.7 on 2025-03-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0098_course_plan_meta_alter_course_plan_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="plan_slug",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="A list of comma separated plan slugs that this course belongs to",
                max_length=150,
                null=True,
            ),
        ),
    ]
